"""initial schema

Revision ID: 6bc24200b4e6
Revises: 
Create Date: 2026-04-11 15:34:23.439307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc24200b4e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_regime_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.String(length=50), nullable=False, comment='Asset class (es. us_equities_growth, gold, bitcoin)'),
    sa.Column('regime', sa.String(length=30), nullable=False, comment='Regime macro'),
    sa.Column('hit_rate', sa.Float(), nullable=False, comment='Percentuale periodi storici con outperformance (0-1)'),
    sa.Column('avg_return_12m', sa.Float(), nullable=False, comment='Rendimento medio annualizzato'),
    sa.Column('volatility_in_regime', sa.Float(), nullable=False, comment='Deviazione standard nel regime'),
    sa.Column('sharpe_in_regime', sa.Float(), nullable=False, comment='Sharpe ratio nel regime'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asset_regime_perf_asset_regime', 'asset_regime_performance', ['asset_class', 'regime'], unique=True)
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False, comment='Data esecuzione backtest'),
    sa.Column('period_start', sa.Date(), nullable=False, comment='Inizio periodo test'),
    sa.Column('period_end', sa.Date(), nullable=False, comment='Fine periodo test'),
    sa.Column('asset_class', sa.String(length=50), nullable=False, comment='Asset class testato'),
    sa.Column('predicted_regime', sa.String(length=30), nullable=False, comment='Regime predetto dal modello'),
    sa.Column('actual_return', sa.Float(), nullable=False, comment='Rendimento effettivo nel periodo'),
    sa.Column('predicted_score', sa.Float(), nullable=False, comment='Score assegnato dal modello'),
    sa.Column('hit', sa.Integer(), nullable=False, comment='1 se predizione corretta (outperformance), 0 altrimenti'),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON dettagli backtest'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_results_asset_period', 'backtest_results', ['asset_class', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_backtest_results_run_date', 'backtest_results', ['run_date'], unique=False)
    op.create_table('daily_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data segnale'),
    sa.Column('asset_class', sa.String(length=50), nullable=False, comment='Asset class'),
    sa.Column('final_score', sa.Float(), nullable=False, comment='Score finale 0-100'),
    sa.Column('regime_component', sa.Float(), nullable=False, comment='Componente regime-based'),
    sa.Column('secular_trend_bonus', sa.Float(), nullable=False, comment='Bonus trend secolare (dedollarizzazione, fase 2)'),
    sa.Column('news_signal', sa.Float(), nullable=False, comment='Segnale news con decay esponenziale 7gg (fase 2)'),
    sa.Column('momentum_penalty', sa.Float(), nullable=False, comment='Penalita se asset sopravvalutato'),
    sa.Column('breakdown', sa.Text(), nullable=True, comment='JSON breakdown componenti per debug'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_signals_date', 'daily_signals', ['date'], unique=False)
    op.create_index('ix_daily_signals_date_asset', 'daily_signals', ['date', 'asset_class'], unique=True)
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data osservazione'),
    sa.Column('series_id', sa.String(length=50), nullable=False, comment='Codice FRED (es. GDP, CPIAUCSL)'),
    sa.Column('value', sa.Float(), nullable=False, comment='Valore raw'),
    sa.Column('roc_3m', sa.Float(), nullable=True, comment='Rate of change 3 mesi'),
    sa.Column('roc_6m', sa.Float(), nullable=True, comment='Rate of change 6 mesi'),
    sa.Column('roc_12m', sa.Float(), nullable=True, comment='Rate of change 12 mesi'),
    sa.Column('zscore_12m', sa.Float(), nullable=True, comment='Z-score rolling 12 mesi'),
    sa.Column('zscore_36m', sa.Float(), nullable=True, comment='Z-score rolling 36 mesi'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_macro_indicators_date_series', 'macro_indicators', ['date', 'series_id'], unique=True)
    op.create_index('ix_macro_indicators_series_date', 'macro_indicators', ['series_id', 'date'], unique=False)
    op.create_table('news_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data notizia'),
    sa.Column('source', sa.String(length=100), nullable=False, comment='Fonte (es. reuters, bloomberg, youtube)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Titolo o descrizione'),
    sa.Column('content_summary', sa.Text(), nullable=True, comment='Riassunto contenuto (Claude API)'),
    sa.Column('sentiment_score', sa.Float(), nullable=False, comment='Score sentiment -1 (bearish) a +1 (bullish)'),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='Rilevanza per macro analysis 0-1'),
    sa.Column('affected_assets', sa.Text(), nullable=True, comment='JSON lista asset class impattati'),
    sa.Column('decay_weight', sa.Float(), nullable=False, comment='Peso con decay esponenziale (dimezza ogni 7gg)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_signals_date', 'news_signals', ['date'], unique=False)
    op.create_index('ix_news_signals_source_date', 'news_signals', ['source', 'date'], unique=False)
    op.create_table('regime_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data classificazione'),
    sa.Column('regime', sa.String(length=30), nullable=False, comment='Regime: growth, slowdown, recession, recovery, stagflation, goldilocks'),
    sa.Column('probability_growth', sa.Float(), nullable=False, comment='Probabilita regime growth'),
    sa.Column('probability_slowdown', sa.Float(), nullable=False, comment='Probabilita regime slowdown'),
    sa.Column('probability_recession', sa.Float(), nullable=False, comment='Probabilita regime recession'),
    sa.Column('probability_recovery', sa.Float(), nullable=False, comment='Probabilita regime recovery'),
    sa.Column('probability_stagflation', sa.Float(), nullable=False, comment='Probabilita regime stagflation'),
    sa.Column('probability_goldilocks', sa.Float(), nullable=False, comment='Probabilita regime goldilocks'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score 0-1 (concordanza condizioni)'),
    sa.Column('conditions_met', sa.Text(), nullable=True, comment='JSON con dettaglio condizioni soddisfatte'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Ultimo aggiornamento'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_index('ix_regime_classifications_date', 'regime_classifications', ['date'], unique=False)
    op.create_index('ix_regime_classifications_regime', 'regime_classifications', ['regime'], unique=False)
    op.create_table('secular_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Data osservazione'),
    sa.Column('trend_name', sa.String(length=50), nullable=False, comment='Nome trend (dedollarization, multipolar_shift, energy_transition)'),
    sa.Column('score', sa.Float(), nullable=False, comment='Score trend 0-1 (intensita)'),
    sa.Column('components', sa.Text(), nullable=True, comment='JSON breakdown componenti del trend'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_secular_trends_date_name', 'secular_trends', ['date', 'trend_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secular_trends_date_name', table_name='secular_trends')
    op.drop_table('secular_trends')
    op.drop_index('ix_regime_classifications_regime', table_name='regime_classifications')
    op.drop_index('ix_regime_classifications_date', table_name='regime_classifications')
    op.drop_table('regime_classifications')
    op.drop_index('ix_news_signals_source_date', table_name='news_signals')
    op.drop_index('ix_news_signals_date', table_name='news_signals')
    op.drop_table('news_signals')
    op.drop_index('ix_macro_indicators_series_date', table_name='macro_indicators')
    op.drop_index('ix_macro_indicators_date_series', table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index('ix_daily_signals_date_asset', table_name='daily_signals')
    op.drop_index('ix_daily_signals_date', table_name='daily_signals')
    op.drop_table('daily_signals')
    op.drop_index('ix_backtest_results_run_date', table_name='backtest_results')
    op.drop_index('ix_backtest_results_asset_period', table_name='backtest_results')
    op.drop_table('backtest_results')
    op.drop_index('ix_asset_regime_perf_asset_regime', table_name='asset_regime_performance')
    op.drop_table('asset_regime_performance')
    # ### end Alembic commands ###
