"""Tier 8 — Dataset esteso di episodi storici per training/validation ML.

18 episodi labeled tra 1970-2024, ognuno con:
- Indicators medi (gdp_roc, cpi_yoy, unrate, vix, fed_funds, ...)
- True regime label (manualmente assegnato basato su consensus storico)
- Actual top-3 asset (performance reali documentate)
- NBER recession flag

Ground truth labels:
- reflation: 1983-89, 2003-07, 2009-13, 2017-19, 2020-21 post-COVID
- stagflation: 1973-75, 1979-82, 2022
- deflation: 1990-91, 2001, 2008-09, 2020 Q1, 2015-16 disinflation scare
- goldilocks: 1995-99, 2013-19 (parziale), 2024

Source: NBER cycle dates, FRED data, BLS historical CPI/unrate, Yahoo asset returns.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class HistoricalEpisode:
    """Singolo episodio storico labeled."""
    name: str
    start_year: int
    end_year: int
    true_regime: str  # reflation|stagflation|deflation|goldilocks
    indicators: dict[str, float]
    actual_top3: set[str] = field(default_factory=set)
    actual_top5: set[str] = field(default_factory=set)
    nber_recession: bool = False
    notes: str = ""


HISTORICAL_EPISODES: list[HistoricalEpisode] = [
    HistoricalEpisode(
        name="1973-75 OPEC stagflation",
        start_year=1973, end_year=1975,
        true_regime="stagflation",
        indicators={
            "gdp_roc": -2.5, "cpi_yoy": 10.0, "unrate": 8.0, "unrate_roc": 0.5,
            "vix": 25.0, "fed_funds": 8.0, "breakeven_10y": 4.0,
            "baa_10y_spread": 2.5, "pmi": 42.0, "yield_curve_spread": 0.5,
            "nfci": 0.5, "core_pce_yoy": 8.0, "consumer_sentiment": 60.0,
            "claims_roc": 5.0, "lei_roc": -2.0, "indpro_yoy": -5.0,
            "payrolls_yoy": -0.5, "housing_starts_yoy": -15.0,
            "acm_term_premium": 1.5,
        },
        actual_top3={"energy", "gold", "broad_commodities"},
        nber_recession=True,
        notes="OPEC oil embargo, double-digit CPI, severe stagflation.",
    ),
    HistoricalEpisode(
        name="1980 Volcker recession #1",
        start_year=1980, end_year=1980,
        true_regime="stagflation",
        indicators={
            "gdp_roc": -1.5, "cpi_yoy": 13.5, "unrate": 7.5, "unrate_roc": 1.0,
            "vix": 22.0, "fed_funds": 20.0, "breakeven_10y": 5.0,
            "baa_10y_spread": 3.5, "pmi": 38.0, "yield_curve_spread": -2.5,
            "nfci": 0.8, "core_pce_yoy": 10.0, "consumer_sentiment": 58.0,
            "claims_roc": 12.0, "lei_roc": -4.0, "indpro_yoy": -5.5,
            "payrolls_yoy": -0.8, "housing_starts_yoy": -25.0,
            "acm_term_premium": 1.8,
        },
        actual_top3={"gold", "energy", "broad_commodities"},
        nber_recession=True,
        notes="Volcker aggressive rate hikes, CPI peak 14.6%.",
    ),
    HistoricalEpisode(
        name="1981-82 Volcker double-dip",
        start_year=1981, end_year=1982,
        true_regime="stagflation",
        indicators={
            "gdp_roc": -2.0, "cpi_yoy": 7.0, "unrate": 10.5, "unrate_roc": 1.5,
            "vix": 20.0, "fed_funds": 14.0, "breakeven_10y": 3.0,
            "baa_10y_spread": 4.0, "pmi": 37.0, "yield_curve_spread": 0.5,
            "nfci": 0.7, "core_pce_yoy": 6.0, "consumer_sentiment": 65.0,
            "claims_roc": 18.0, "lei_roc": -5.0, "indpro_yoy": -7.0,
            "payrolls_yoy": -1.5, "housing_starts_yoy": -30.0,
            "acm_term_premium": 1.5,
        },
        actual_top3={"us_bonds_long", "us_bonds_short", "gold"},
        nber_recession=True,
        notes="Disinflation recession. CPI scendendo da 13 a 4%, ma economy crash. "
              "Borderline stagflation→deflation transition.",
    ),
    HistoricalEpisode(
        name="1983-89 Reagan boom reflation",
        start_year=1983, end_year=1989,
        true_regime="reflation",
        indicators={
            "gdp_roc": 4.5, "cpi_yoy": 3.5, "unrate": 6.0, "unrate_roc": -0.4,
            "vix": 18.0, "fed_funds": 7.0, "breakeven_10y": 3.0,
            "baa_10y_spread": 2.0, "pmi": 56.0, "yield_curve_spread": 1.5,
            "nfci": -0.2, "core_pce_yoy": 3.5, "consumer_sentiment": 90.0,
            "claims_roc": -3.0, "lei_roc": 2.0, "indpro_yoy": 4.5,
            "payrolls_yoy": 3.0, "housing_starts_yoy": 5.0,
            "acm_term_premium": 0.8,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        nber_recession=False,
        notes="Greenspan post-Volcker recovery, supply-side boom.",
    ),
    HistoricalEpisode(
        name="1990-91 S&L crisis recession",
        start_year=1990, end_year=1991,
        true_regime="deflation",
        indicators={
            "gdp_roc": -1.0, "cpi_yoy": 5.0, "unrate": 7.0, "unrate_roc": 0.8,
            "vix": 26.0, "fed_funds": 5.5, "breakeven_10y": 2.5,
            "baa_10y_spread": 3.0, "pmi": 43.0, "yield_curve_spread": 1.0,
            "nfci": 0.6, "core_pce_yoy": 4.5, "consumer_sentiment": 65.0,
            "claims_roc": 8.0, "lei_roc": -2.5, "indpro_yoy": -2.0,
            "payrolls_yoy": -0.5, "housing_starts_yoy": -20.0,
            "acm_term_premium": 1.0,
        },
        actual_top3={"us_bonds_long", "us_bonds_short", "gold"},
        nber_recession=True,
        notes="Savings & Loan banking crisis, oil price spike from Gulf War.",
    ),
    HistoricalEpisode(
        name="1995-99 Greenspan goldilocks",
        start_year=1995, end_year=1999,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 4.0, "cpi_yoy": 2.2, "unrate": 4.5, "unrate_roc": -0.3,
            "vix": 18.0, "fed_funds": 5.0, "breakeven_10y": 2.0,
            "baa_10y_spread": 1.5, "pmi": 54.0, "yield_curve_spread": 0.8,
            "nfci": -0.4, "core_pce_yoy": 2.0, "consumer_sentiment": 105.0,
            "claims_roc": -4.0, "lei_roc": 1.5, "indpro_yoy": 4.5,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 3.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "international_dm_equities"},
        nber_recession=False,
        notes="Productivity boom, disinflation + growth. Classic goldilocks.",
    ),
    HistoricalEpisode(
        name="2001 dotcom bust",
        start_year=2001, end_year=2001,
        true_regime="deflation",
        indicators={
            "gdp_roc": 0.5, "cpi_yoy": 3.0, "unrate": 4.7, "unrate_roc": 0.4,
            "vix": 25.0, "fed_funds": 4.0, "breakeven_10y": 2.0,
            "baa_10y_spread": 2.8, "pmi": 43.0, "yield_curve_spread": 0.3,
            "nfci": 0.4, "core_pce_yoy": 2.0, "consumer_sentiment": 85.0,
            "claims_roc": 9.0, "lei_roc": -2.0, "indpro_yoy": -4.0,
            "payrolls_yoy": 0.0, "housing_starts_yoy": 0.0,
            "acm_term_premium": 0.6,
        },
        actual_top3={"us_bonds_long", "gold", "cash_money_market"},
        nber_recession=True,
        notes="Tech bubble pop + 9/11 shock. Disinflationary recession.",
    ),
    HistoricalEpisode(
        name="2003-07 housing boom reflation",
        start_year=2003, end_year=2007,
        true_regime="reflation",
        indicators={
            "gdp_roc": 3.0, "cpi_yoy": 3.0, "unrate": 5.0, "unrate_roc": -0.2,
            "vix": 14.0, "fed_funds": 4.0, "breakeven_10y": 2.5,
            "baa_10y_spread": 1.7, "pmi": 55.0, "yield_curve_spread": 0.7,
            "nfci": -0.5, "core_pce_yoy": 2.3, "consumer_sentiment": 90.0,
            "claims_roc": -2.0, "lei_roc": 1.5, "indpro_yoy": 3.0,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 6.0,
            "acm_term_premium": 0.4,
        },
        actual_top3={"em_equities", "broad_commodities", "energy"},
        nber_recession=False,
        notes="Greenspan low rates, EM boom, commodity supercycle.",
    ),
    HistoricalEpisode(
        name="2008-09 GFC deflation crash",
        start_year=2008, end_year=2009,
        true_regime="deflation",
        indicators={
            "gdp_roc": -4.0, "cpi_yoy": 1.0, "unrate": 8.0, "unrate_roc": 1.2,
            "vix": 50.0, "fed_funds": 2.0, "breakeven_10y": 0.5,
            "baa_10y_spread": 6.0, "pmi": 38.0, "yield_curve_spread": 2.0,
            "nfci": 2.0, "core_pce_yoy": 1.5, "consumer_sentiment": 55.0,
            "claims_roc": 20.0, "lei_roc": -7.0, "indpro_yoy": -10.0,
            "payrolls_yoy": -3.5, "housing_starts_yoy": -45.0,
            "acm_term_premium": 1.0,
        },
        actual_top3={"us_bonds_long", "us_bonds_short", "gold"},
        nber_recession=True,
        notes="Global Financial Crisis. Lehman collapse, deleveraging.",
    ),
    HistoricalEpisode(
        name="2009-13 post-GFC QE reflation",
        start_year=2009, end_year=2013,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.5, "cpi_yoy": 1.8, "unrate": 8.5, "unrate_roc": -0.5,
            "vix": 22.0, "fed_funds": 0.25, "breakeven_10y": 2.0,
            "baa_10y_spread": 2.5, "pmi": 53.0, "yield_curve_spread": 2.5,
            "nfci": -0.3, "core_pce_yoy": 1.5, "consumer_sentiment": 75.0,
            "claims_roc": -5.0, "lei_roc": 1.0, "indpro_yoy": 4.0,
            "payrolls_yoy": 1.5, "housing_starts_yoy": 25.0,
            "acm_term_premium": 0.8,
        },
        actual_top3={"us_equities_growth", "real_estate_reits", "us_equities_value"},
        nber_recession=False,
        notes="ZIRP + QE, slow recovery. Equity + REIT supercycle.",
    ),
    HistoricalEpisode(
        name="2015-16 disinflation scare",
        start_year=2015, end_year=2016,
        true_regime="deflation",
        indicators={
            "gdp_roc": 1.5, "cpi_yoy": 0.5, "unrate": 5.0, "unrate_roc": 0.0,
            "vix": 21.0, "fed_funds": 0.5, "breakeven_10y": 1.4,
            "baa_10y_spread": 3.2, "pmi": 49.0, "yield_curve_spread": 1.5,
            "nfci": 0.3, "core_pce_yoy": 1.5, "consumer_sentiment": 92.0,
            "claims_roc": -1.0, "lei_roc": 0.2, "indpro_yoy": -1.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 8.0,
            "acm_term_premium": 0.2,
        },
        actual_top3={"us_bonds_long", "gold", "us_equities_growth"},
        nber_recession=False,
        notes="Oil crash 2014-15, China devaluation, CPI <1%. "
              "Disinflation scare without full recession.",
    ),
    HistoricalEpisode(
        name="2017-19 Trump trade reflation",
        start_year=2017, end_year=2019,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 2.8, "cpi_yoy": 2.0, "unrate": 4.0, "unrate_roc": -0.3,
            "vix": 14.0, "fed_funds": 2.0, "breakeven_10y": 2.0,
            "baa_10y_spread": 1.6, "pmi": 55.0, "yield_curve_spread": 0.5,
            "nfci": -0.4, "core_pce_yoy": 1.9, "consumer_sentiment": 100.0,
            "claims_roc": -3.0, "lei_roc": 1.0, "indpro_yoy": 2.8,
            "payrolls_yoy": 1.7, "housing_starts_yoy": 4.0,
            "acm_term_premium": 0.0,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "international_dm_equities"},
        nber_recession=False,
        notes="Tax cuts, low inflation, low unemployment. Goldilocks 2.0.",
    ),
    HistoricalEpisode(
        name="2020 Q1 COVID crash",
        start_year=2020, end_year=2020,
        true_regime="deflation",
        indicators={
            "gdp_roc": -9.0, "cpi_yoy": 0.5, "unrate": 14.0, "unrate_roc": 5.0,
            "vix": 60.0, "fed_funds": 0.25, "breakeven_10y": 1.0,
            "baa_10y_spread": 4.0, "pmi": 36.0, "yield_curve_spread": 1.0,
            "nfci": 1.0, "core_pce_yoy": 1.2, "consumer_sentiment": 70.0,
            "claims_roc": 50.0, "lei_roc": -10.0, "indpro_yoy": -12.0,
            "payrolls_yoy": -13.0, "housing_starts_yoy": -25.0,
            "acm_term_premium": 0.3,
        },
        actual_top3={"us_bonds_long", "gold", "cash_money_market"},
        nber_recession=True,
        notes="COVID lockdown shock. Massive deflation crash + recovery.",
    ),
    HistoricalEpisode(
        name="2020-21 post-COVID reflation",
        start_year=2020, end_year=2021,
        true_regime="reflation",
        indicators={
            "gdp_roc": 5.0, "cpi_yoy": 4.0, "unrate": 4.5, "unrate_roc": -0.5,
            "vix": 18.0, "fed_funds": 0.25, "breakeven_10y": 2.3,
            "baa_10y_spread": 2.0, "pmi": 58.0, "yield_curve_spread": 1.5,
            "nfci": -0.5, "core_pce_yoy": 3.5, "consumer_sentiment": 85.0,
            "claims_roc": -10.0, "lei_roc": 3.0, "indpro_yoy": 6.0,
            "payrolls_yoy": 3.0, "housing_starts_yoy": 12.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_equities_growth", "em_equities", "bitcoin"},
        nber_recession=False,
        notes="Massive QE + fiscal stimulus, asset inflation, crypto boom.",
    ),
    HistoricalEpisode(
        name="2022 inflation surge",
        start_year=2022, end_year=2022,
        true_regime="stagflation",
        indicators={
            "gdp_roc": 1.5, "cpi_yoy": 8.0, "unrate": 3.7, "unrate_roc": 0.0,
            "vix": 25.0, "fed_funds": 4.5, "breakeven_10y": 2.5,
            "baa_10y_spread": 2.3, "pmi": 49.0, "yield_curve_spread": 0.0,
            "nfci": 0.2, "core_pce_yoy": 5.0, "consumer_sentiment": 62.0,
            "claims_roc": 0.0, "lei_roc": -1.0, "indpro_yoy": 1.0,
            "payrolls_yoy": 2.5, "housing_starts_yoy": -10.0,
            "acm_term_premium": 0.4,
        },
        actual_top3={"energy", "broad_commodities", "cash_money_market"},
        nber_recession=False,
        notes="Russia/Ukraine war + supply chain. Fed aggressive hikes.",
    ),
    HistoricalEpisode(
        name="2023 banking crisis (SVB)",
        start_year=2023, end_year=2023,
        true_regime="deflation",
        indicators={
            "gdp_roc": 2.5, "cpi_yoy": 4.0, "unrate": 3.7, "unrate_roc": 0.1,
            "vix": 26.0, "fed_funds": 5.0, "breakeven_10y": 2.3,
            "baa_10y_spread": 2.5, "pmi": 47.0, "yield_curve_spread": -0.8,
            "nfci": 0.5, "core_pce_yoy": 4.0, "consumer_sentiment": 65.0,
            "claims_roc": 5.0, "lei_roc": -0.5, "indpro_yoy": 0.5,
            "payrolls_yoy": 2.0, "housing_starts_yoy": -8.0,
            "acm_term_premium": 0.3,
        },
        actual_top3={"us_bonds_long", "gold", "us_equities_growth"},
        nber_recession=False,
        notes="SVB/Credit Suisse collapse, brief deflation scare. "
              "Avoided full crisis via Fed BTFP backstop.",
    ),
    HistoricalEpisode(
        name="2024 disinflation goldilocks",
        start_year=2024, end_year=2024,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 2.5, "cpi_yoy": 2.5, "unrate": 3.9, "unrate_roc": 0.05,
            "vix": 14.0, "fed_funds": 5.0, "breakeven_10y": 2.3,
            "baa_10y_spread": 1.6, "pmi": 52.0, "yield_curve_spread": 0.3,
            "nfci": -0.4, "core_pce_yoy": 2.5, "consumer_sentiment": 80.0,
            "claims_roc": -1.0, "lei_roc": 0.5, "indpro_yoy": 1.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 2.0,
            "acm_term_premium": -0.2,
        },
        actual_top3={"us_equities_growth", "bitcoin", "gold"},
        nber_recession=False,
        notes="Soft landing disinflation, AI rally, BTC ETF approval.",
    ),
    HistoricalEpisode(
        name="2018 Q4 sell-off",
        start_year=2018, end_year=2018,
        true_regime="deflation",
        indicators={
            "gdp_roc": 2.5, "cpi_yoy": 2.2, "unrate": 3.8, "unrate_roc": -0.05,
            "vix": 26.0, "fed_funds": 2.5, "breakeven_10y": 1.8,
            "baa_10y_spread": 2.0, "pmi": 53.0, "yield_curve_spread": 0.3,
            "nfci": 0.2, "core_pce_yoy": 2.0, "consumer_sentiment": 95.0,
            "claims_roc": 2.0, "lei_roc": 0.0, "indpro_yoy": 2.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": -3.0,
            "acm_term_premium": 0.1,
        },
        actual_top3={"us_bonds_long", "cash_money_market", "gold"},
        actual_top5={"us_bonds_long", "cash_money_market", "gold", "us_bonds_short", "tips_inflation_bonds"},
        nber_recession=False,
        notes="Fed QT + China tariff war. Q4 -20% S&P drawdown.",
    ),
    # === TIER 9 EXTENDED EPISODES (pre-1970 + intra-period granularity) ===
    HistoricalEpisode(
        name="1929-33 Great Depression",
        start_year=1929, end_year=1933,
        true_regime="deflation",
        indicators={
            "gdp_roc": -10.0, "cpi_yoy": -8.0, "unrate": 22.0, "unrate_roc": 4.0,
            "vix": 60.0, "fed_funds": 1.5, "breakeven_10y": -3.0,
            "baa_10y_spread": 7.5, "pmi": 30.0, "yield_curve_spread": 2.0,
            "nfci": 3.0, "core_pce_yoy": -7.0, "consumer_sentiment": 35.0,
            "claims_roc": 30.0, "lei_roc": -8.0, "indpro_yoy": -15.0,
            "payrolls_yoy": -10.0, "housing_starts_yoy": -60.0,
            "acm_term_premium": 1.5,
        },
        actual_top3={"us_bonds_long", "cash_money_market", "gold"},
        actual_top5={"us_bonds_long", "cash_money_market", "gold", "us_bonds_short", "tips_inflation_bonds"},
        nber_recession=True,
        notes="Severest deflation in US history. CPI -25% cumulative, GDP -30%. "
              "Cash + Treasuries only winners.",
    ),
    HistoricalEpisode(
        name="1937-38 Roosevelt recession",
        start_year=1937, end_year=1938,
        true_regime="deflation",
        indicators={
            "gdp_roc": -3.5, "cpi_yoy": -2.0, "unrate": 15.0, "unrate_roc": 4.0,
            "vix": 35.0, "fed_funds": 1.0, "breakeven_10y": -1.0,
            "baa_10y_spread": 3.5, "pmi": 40.0, "yield_curve_spread": 1.5,
            "nfci": 1.5, "core_pce_yoy": -2.0, "consumer_sentiment": 50.0,
            "claims_roc": 18.0, "lei_roc": -5.0, "indpro_yoy": -12.0,
            "payrolls_yoy": -5.0, "housing_starts_yoy": -25.0,
            "acm_term_premium": 1.2,
        },
        actual_top3={"us_bonds_long", "cash_money_market", "gold"},
        actual_top5={"us_bonds_long", "cash_money_market", "gold", "us_bonds_short", "tips_inflation_bonds"},
        nber_recession=True,
        notes="Premature Fed tightening + budget cuts. Mini-1929 redux.",
    ),
    HistoricalEpisode(
        name="1957-58 Eisenhower recession",
        start_year=1957, end_year=1958,
        true_regime="deflation",
        indicators={
            "gdp_roc": -2.0, "cpi_yoy": 1.5, "unrate": 7.0, "unrate_roc": 1.5,
            "vix": 23.0, "fed_funds": 2.5, "breakeven_10y": 1.5,
            "baa_10y_spread": 2.8, "pmi": 42.0, "yield_curve_spread": 0.8,
            "nfci": 0.5, "core_pce_yoy": 1.8, "consumer_sentiment": 75.0,
            "claims_roc": 12.0, "lei_roc": -3.5, "indpro_yoy": -8.0,
            "payrolls_yoy": -2.5, "housing_starts_yoy": -15.0,
            "acm_term_premium": 0.7,
        },
        actual_top3={"us_bonds_long", "us_bonds_short", "cash_money_market"},
        actual_top5={"us_bonds_long", "us_bonds_short", "cash_money_market", "gold", "us_equities_value"},
        nber_recession=True,
        notes="Cyclical inventory + Fed tight money. Bonds best.",
    ),
    HistoricalEpisode(
        name="1965-69 Vietnam boom reflation",
        start_year=1965, end_year=1969,
        true_regime="reflation",
        indicators={
            "gdp_roc": 4.0, "cpi_yoy": 4.5, "unrate": 3.6, "unrate_roc": -0.2,
            "vix": 16.0, "fed_funds": 5.5, "breakeven_10y": 3.0,
            "baa_10y_spread": 1.8, "pmi": 55.0, "yield_curve_spread": 0.5,
            "nfci": -0.2, "core_pce_yoy": 4.0, "consumer_sentiment": 95.0,
            "claims_roc": -2.0, "lei_roc": 1.5, "indpro_yoy": 5.0,
            "payrolls_yoy": 3.5, "housing_starts_yoy": 4.0,
            "acm_term_premium": 0.9,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "broad_commodities"},
        actual_top5={"us_equities_growth", "us_equities_value", "broad_commodities", "real_estate_reits", "energy"},
        nber_recession=False,
        notes="Vietnam war spending + LBJ Great Society. Pre-stagflation reflation.",
    ),
    HistoricalEpisode(
        name="1969-70 Nixon recession",
        start_year=1969, end_year=1970,
        true_regime="stagflation",
        indicators={
            "gdp_roc": -0.3, "cpi_yoy": 5.5, "unrate": 6.0, "unrate_roc": 0.8,
            "vix": 22.0, "fed_funds": 8.0, "breakeven_10y": 4.5,
            "baa_10y_spread": 2.5, "pmi": 45.0, "yield_curve_spread": -0.3,
            "nfci": 0.4, "core_pce_yoy": 5.0, "consumer_sentiment": 78.0,
            "claims_roc": 8.0, "lei_roc": -2.0, "indpro_yoy": -2.5,
            "payrolls_yoy": 0.0, "housing_starts_yoy": -10.0,
            "acm_term_premium": 1.0,
        },
        actual_top3={"gold", "broad_commodities", "us_bonds_short"},
        actual_top5={"gold", "broad_commodities", "us_bonds_short", "cash_money_market", "energy"},
        nber_recession=True,
        notes="First mild stagflation. Nixon wage-price controls fail.",
    ),
    HistoricalEpisode(
        name="1976-78 pre-OPEC2 stagflation",
        start_year=1976, end_year=1978,
        true_regime="stagflation",
        indicators={
            "gdp_roc": 3.0, "cpi_yoy": 7.0, "unrate": 7.0, "unrate_roc": -0.2,
            "vix": 18.0, "fed_funds": 7.0, "breakeven_10y": 5.0,
            "baa_10y_spread": 2.0, "pmi": 53.0, "yield_curve_spread": 0.8,
            "nfci": 0.0, "core_pce_yoy": 6.5, "consumer_sentiment": 80.0,
            "claims_roc": -2.0, "lei_roc": 1.0, "indpro_yoy": 3.5,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 8.0,
            "acm_term_premium": 1.3,
        },
        actual_top3={"real_estate_reits", "broad_commodities", "gold"},
        actual_top5={"real_estate_reits", "broad_commodities", "gold", "energy", "us_equities_value"},
        nber_recession=False,
        notes="Carter era inflation persistence. Inflation entrenchment phase.",
    ),
    HistoricalEpisode(
        name="1987 Black Monday crash",
        start_year=1987, end_year=1987,
        true_regime="reflation",
        indicators={
            "gdp_roc": 3.5, "cpi_yoy": 4.0, "unrate": 5.7, "unrate_roc": -0.5,
            "vix": 35.0, "fed_funds": 7.0, "breakeven_10y": 3.5,
            "baa_10y_spread": 2.5, "pmi": 56.0, "yield_curve_spread": 0.8,
            "nfci": 0.6, "core_pce_yoy": 3.8, "consumer_sentiment": 88.0,
            "claims_roc": 0.0, "lei_roc": 1.2, "indpro_yoy": 4.5,
            "payrolls_yoy": 3.0, "housing_starts_yoy": -3.0,
            "acm_term_premium": 1.5,
        },
        actual_top3={"us_bonds_long", "gold", "cash_money_market"},
        actual_top5={"us_bonds_long", "gold", "cash_money_market", "us_bonds_short", "tips_inflation_bonds"},
        nber_recession=False,
        notes="Crash -22% in 1 day. Volatility spike but no recession. "
              "Reflation regime, brief flight to safety.",
    ),
    HistoricalEpisode(
        name="1994 bond crisis",
        start_year=1994, end_year=1994,
        true_regime="reflation",
        indicators={
            "gdp_roc": 4.0, "cpi_yoy": 2.6, "unrate": 5.5, "unrate_roc": -0.7,
            "vix": 14.0, "fed_funds": 5.5, "breakeven_10y": 2.8,
            "baa_10y_spread": 1.4, "pmi": 56.0, "yield_curve_spread": 1.0,
            "nfci": 0.0, "core_pce_yoy": 2.3, "consumer_sentiment": 95.0,
            "claims_roc": -3.0, "lei_roc": 1.5, "indpro_yoy": 5.5,
            "payrolls_yoy": 3.0, "housing_starts_yoy": 5.0,
            "acm_term_premium": 1.0,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "broad_commodities"},
        actual_top5={"us_equities_growth", "us_equities_value", "broad_commodities", "international_dm_equities", "energy"},
        nber_recession=False,
        notes="Greenspan surprise tightening, bonds -7%. "
              "Equities held; reflation continued.",
    ),
    HistoricalEpisode(
        name="1998 LTCM/Russia/Asia crisis",
        start_year=1998, end_year=1998,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 4.5, "cpi_yoy": 1.6, "unrate": 4.5, "unrate_roc": -0.3,
            "vix": 28.0, "fed_funds": 5.5, "breakeven_10y": 1.8,
            "baa_10y_spread": 2.3, "pmi": 50.0, "yield_curve_spread": 0.4,
            "nfci": 0.5, "core_pce_yoy": 1.5, "consumer_sentiment": 105.0,
            "claims_roc": 0.0, "lei_roc": 0.5, "indpro_yoy": 3.5,
            "payrolls_yoy": 2.8, "housing_starts_yoy": 5.0,
            "acm_term_premium": 0.7,
        },
        actual_top3={"us_equities_growth", "us_bonds_long", "us_equities_value"},
        actual_top5={"us_equities_growth", "us_bonds_long", "us_equities_value", "real_estate_reits", "cash_money_market"},
        nber_recession=False,
        notes="LTCM bailout, Fed cuts 75bps. Brief flight to safety, "
              "then resumed bull market. Goldilocks survived.",
    ),
    HistoricalEpisode(
        name="2011 European debt crisis",
        start_year=2011, end_year=2011,
        true_regime="deflation",
        indicators={
            "gdp_roc": 1.5, "cpi_yoy": 3.0, "unrate": 9.0, "unrate_roc": -0.1,
            "vix": 30.0, "fed_funds": 0.25, "breakeven_10y": 2.3,
            "baa_10y_spread": 3.5, "pmi": 47.0, "yield_curve_spread": 2.2,
            "nfci": 0.4, "core_pce_yoy": 1.6, "consumer_sentiment": 65.0,
            "claims_roc": 0.0, "lei_roc": 0.3, "indpro_yoy": 2.5,
            "payrolls_yoy": 1.3, "housing_starts_yoy": -2.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_bonds_long", "gold", "cash_money_market"},
        actual_top5={"us_bonds_long", "gold", "cash_money_market", "us_bonds_short", "tips_inflation_bonds"},
        nber_recession=False,
        notes="Eurozone PIIGS crisis. US downgrade. Gold +30%, bonds rally.",
    ),
    HistoricalEpisode(
        name="2014-15 oil crash",
        start_year=2014, end_year=2015,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 2.5, "cpi_yoy": 0.5, "unrate": 5.5, "unrate_roc": -0.5,
            "vix": 18.0, "fed_funds": 0.25, "breakeven_10y": 1.5,
            "baa_10y_spread": 2.0, "pmi": 53.0, "yield_curve_spread": 1.8,
            "nfci": -0.1, "core_pce_yoy": 1.6, "consumer_sentiment": 95.0,
            "claims_roc": -3.0, "lei_roc": 0.8, "indpro_yoy": 1.5,
            "payrolls_yoy": 2.0, "housing_starts_yoy": 8.0,
            "acm_term_premium": 0.0,
        },
        actual_top3={"us_equities_growth", "us_bonds_long", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_bonds_long", "real_estate_reits", "us_equities_value", "international_dm_equities"},
        nber_recession=False,
        notes="WTI 100→30 USD. CPI near zero. Disinflation boost equities + bonds.",
    ),
    HistoricalEpisode(
        name="2019 Q4 mid-cycle slowdown",
        start_year=2019, end_year=2019,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 2.2, "cpi_yoy": 2.0, "unrate": 3.7, "unrate_roc": -0.2,
            "vix": 14.0, "fed_funds": 2.0, "breakeven_10y": 1.8,
            "baa_10y_spread": 1.7, "pmi": 50.0, "yield_curve_spread": 0.2,
            "nfci": -0.4, "core_pce_yoy": 1.7, "consumer_sentiment": 98.0,
            "claims_roc": -2.0, "lei_roc": 0.5, "indpro_yoy": 0.5,
            "payrolls_yoy": 1.5, "housing_starts_yoy": 3.0,
            "acm_term_premium": -0.1,
        },
        actual_top3={"us_equities_growth", "us_bonds_long", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_bonds_long", "real_estate_reits", "us_equities_value", "gold"},
        nber_recession=False,
        notes="Fed pivot dovish, repo crisis Sep. Mid-cycle slowdown averted.",
    ),
    HistoricalEpisode(
        name="2025 AI cycle reflation",
        start_year=2025, end_year=2025,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.8, "cpi_yoy": 2.8, "unrate": 4.1, "unrate_roc": 0.05,
            "vix": 15.0, "fed_funds": 4.5, "breakeven_10y": 2.4,
            "baa_10y_spread": 1.6, "pmi": 53.0, "yield_curve_spread": 0.4,
            "nfci": -0.3, "core_pce_yoy": 2.6, "consumer_sentiment": 82.0,
            "claims_roc": 1.0, "lei_roc": 0.6, "indpro_yoy": 1.8,
            "payrolls_yoy": 1.6, "housing_starts_yoy": 1.0,
            "acm_term_premium": -0.1,
        },
        actual_top3={"us_equities_growth", "bitcoin", "gold"},
        actual_top5={"us_equities_growth", "bitcoin", "gold", "us_equities_value", "broad_commodities"},
        nber_recession=False,
        notes="AI capex supercycle, Fed cutting gradually. Equities + crypto.",
    ),
    # === T9-AUDIT growth-era episodi (gold bias correction) ===
    HistoricalEpisode(
        name="1955 Eisenhower mid-cycle expansion",
        start_year=1955, end_year=1956,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 4.2, "cpi_yoy": 0.5, "unrate": 4.2, "unrate_roc": -0.3,
            "vix": 14.0, "fed_funds": 2.5, "breakeven_10y": 1.5,
            "baa_10y_spread": 1.2, "pmi": 56.0, "yield_curve_spread": 0.6,
            "nfci": -0.3, "core_pce_yoy": 0.6, "consumer_sentiment": 95.0,
            "claims_roc": -3.0, "lei_roc": 1.2, "indpro_yoy": 5.0,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 8.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "us_bonds_short"},
        nber_recession=False,
        notes="Post-Korean War expansion, low inflation, mid-cycle.",
    ),
    HistoricalEpisode(
        name="1962-65 Kennedy/Johnson expansion",
        start_year=1962, end_year=1965,
        true_regime="reflation",
        indicators={
            "gdp_roc": 5.5, "cpi_yoy": 1.5, "unrate": 5.0, "unrate_roc": -0.4,
            "vix": 15.0, "fed_funds": 3.5, "breakeven_10y": 2.0,
            "baa_10y_spread": 1.3, "pmi": 58.0, "yield_curve_spread": 0.8,
            "nfci": -0.4, "core_pce_yoy": 1.3, "consumer_sentiment": 100.0,
            "claims_roc": -4.0, "lei_roc": 1.8, "indpro_yoy": 6.5,
            "payrolls_yoy": 3.2, "housing_starts_yoy": 6.0,
            "acm_term_premium": 0.6,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "broad_commodities"},
        nber_recession=False,
        notes="JFK tax cut + Vietnam early. Strong growth, low inflation.",
    ),
    HistoricalEpisode(
        name="1985 Plaza Accord disinflation reflation",
        start_year=1985, end_year=1986,
        true_regime="reflation",
        indicators={
            "gdp_roc": 4.0, "cpi_yoy": 3.5, "unrate": 7.0, "unrate_roc": -0.4,
            "vix": 17.0, "fed_funds": 7.5, "breakeven_10y": 3.0,
            "baa_10y_spread": 2.0, "pmi": 55.0, "yield_curve_spread": 1.2,
            "nfci": -0.1, "core_pce_yoy": 3.4, "consumer_sentiment": 92.0,
            "claims_roc": -2.5, "lei_roc": 1.5, "indpro_yoy": 3.5,
            "payrolls_yoy": 2.8, "housing_starts_yoy": 4.0,
            "acm_term_premium": 0.7,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "em_equities"},
        nber_recession=False,
        notes="Plaza Accord USD devaluation, disinflation success, EAFE outperform.",
    ),
    HistoricalEpisode(
        name="1992-94 post-Gulf War recovery reflation",
        start_year=1992, end_year=1994,
        true_regime="reflation",
        indicators={
            "gdp_roc": 3.5, "cpi_yoy": 3.0, "unrate": 6.5, "unrate_roc": -0.5,
            "vix": 15.0, "fed_funds": 4.0, "breakeven_10y": 2.7,
            "baa_10y_spread": 1.4, "pmi": 55.0, "yield_curve_spread": 1.5,
            "nfci": -0.2, "core_pce_yoy": 2.8, "consumer_sentiment": 90.0,
            "claims_roc": -3.5, "lei_roc": 1.3, "indpro_yoy": 4.5,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 6.0,
            "acm_term_premium": 0.9,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "em_equities"},
        actual_top5={"us_equities_growth", "us_equities_value", "em_equities",
                     "real_estate_reits", "international_dm_equities"},
        nber_recession=False,
        notes="Clinton recovery, peace dividend, emerging markets boom early.",
    ),
    # === TIER 9-AUDIT expansion (37 → 50, sub-cycles per ridurre boundary errors) ===
    HistoricalEpisode(
        name="1962 Cuban missile crisis (V-shape)",
        start_year=1962, end_year=1962,
        true_regime="deflation",
        indicators={
            "gdp_roc": 0.5, "cpi_yoy": 1.0, "unrate": 5.5, "unrate_roc": 0.2,
            "vix": 28.0, "fed_funds": 3.0, "breakeven_10y": 1.2,
            "baa_10y_spread": 2.5, "pmi": 47.0, "yield_curve_spread": 0.5,
            "nfci": 0.4, "core_pce_yoy": 1.2, "consumer_sentiment": 70.0,
            "claims_roc": 4.0, "lei_roc": -1.0, "indpro_yoy": 0.5,
            "payrolls_yoy": 0.8, "housing_starts_yoy": -3.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_bonds_long", "gold", "cash_money_market"},
        actual_top5={"us_bonds_long", "gold", "cash_money_market",
                     "us_bonds_short", "us_equities_value"},
        nber_recession=False,
        notes="Geopolitical scare, V-shape recovery. Brief defensive flight.",
    ),
    HistoricalEpisode(
        name="1971 Nixon shock (pre-stagflation)",
        start_year=1971, end_year=1972,
        true_regime="reflation",
        indicators={
            "gdp_roc": 3.5, "cpi_yoy": 4.0, "unrate": 5.5, "unrate_roc": -0.3,
            "vix": 18.0, "fed_funds": 4.5, "breakeven_10y": 3.5,
            "baa_10y_spread": 1.8, "pmi": 56.0, "yield_curve_spread": 1.0,
            "nfci": -0.1, "core_pce_yoy": 3.8, "consumer_sentiment": 85.0,
            "claims_roc": -2.0, "lei_roc": 1.2, "indpro_yoy": 4.0,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 8.0,
            "acm_term_premium": 0.8,
        },
        actual_top3={"us_equities_growth", "real_estate_reits", "us_equities_value"},
        actual_top5={"us_equities_growth", "real_estate_reits", "us_equities_value",
                     "international_dm_equities", "broad_commodities"},
        nber_recession=False,
        notes="Gold standard fine, dollar devaluation. Reflation late before OPEC.",
    ),
    HistoricalEpisode(
        name="1979 Volcker shock peak",
        start_year=1979, end_year=1979,
        true_regime="stagflation",
        indicators={
            "gdp_roc": 1.0, "cpi_yoy": 11.5, "unrate": 5.9, "unrate_roc": 0.3,
            "vix": 24.0, "fed_funds": 13.5, "breakeven_10y": 6.0,
            "baa_10y_spread": 3.0, "pmi": 50.0, "yield_curve_spread": -1.0,
            "nfci": 0.6, "core_pce_yoy": 8.5, "consumer_sentiment": 62.0,
            "claims_roc": 5.0, "lei_roc": -2.0, "indpro_yoy": 1.5,
            "payrolls_yoy": 1.0, "housing_starts_yoy": -15.0,
            "acm_term_premium": 1.6,
        },
        actual_top3={"gold", "broad_commodities", "energy"},
        actual_top5={"gold", "broad_commodities", "energy",
                     "cash_money_market", "us_equities_value"},
        nber_recession=False,
        notes="Volcker hikes started, gold parabolic, real assets best.",
    ),
    HistoricalEpisode(
        name="1991 post-recession recovery",
        start_year=1991, end_year=1992,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.8, "cpi_yoy": 3.2, "unrate": 7.0, "unrate_roc": -0.3,
            "vix": 20.0, "fed_funds": 4.0, "breakeven_10y": 2.8,
            "baa_10y_spread": 1.8, "pmi": 52.0, "yield_curve_spread": 1.5,
            "nfci": -0.1, "core_pce_yoy": 3.0, "consumer_sentiment": 78.0,
            "claims_roc": -3.0, "lei_roc": 1.0, "indpro_yoy": 3.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 12.0,
            "acm_term_premium": 0.9,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "us_bonds_short"},
        nber_recession=False,
        notes="Bush-Clinton transition recovery. Equities + housing.",
    ),
    HistoricalEpisode(
        name="1996 Greenspan irrational exuberance mid",
        start_year=1996, end_year=1996,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 3.8, "cpi_yoy": 2.9, "unrate": 5.4, "unrate_roc": -0.2,
            "vix": 16.0, "fed_funds": 5.25, "breakeven_10y": 2.5,
            "baa_10y_spread": 1.4, "pmi": 53.0, "yield_curve_spread": 0.9,
            "nfci": -0.3, "core_pce_yoy": 2.4, "consumer_sentiment": 100.0,
            "claims_roc": -3.5, "lei_roc": 1.2, "indpro_yoy": 4.0,
            "payrolls_yoy": 2.5, "housing_starts_yoy": 4.0,
            "acm_term_premium": 0.6,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "us_bonds_short"},
        nber_recession=False,
        notes="Pre-bubble goldilocks pure. Productivity boom era.",
    ),
    HistoricalEpisode(
        name="2002 post-9/11 stimulus reflation",
        start_year=2002, end_year=2002,
        true_regime="reflation",
        indicators={
            "gdp_roc": 1.8, "cpi_yoy": 1.6, "unrate": 5.8, "unrate_roc": 0.1,
            "vix": 27.0, "fed_funds": 1.75, "breakeven_10y": 1.8,
            "baa_10y_spread": 2.3, "pmi": 51.0, "yield_curve_spread": 2.5,
            "nfci": 0.0, "core_pce_yoy": 1.8, "consumer_sentiment": 89.0,
            "claims_roc": 1.0, "lei_roc": 0.5, "indpro_yoy": 0.5,
            "payrolls_yoy": -0.5, "housing_starts_yoy": 6.0,
            "acm_term_premium": 0.8,
        },
        actual_top3={"us_equities_value", "real_estate_reits", "us_bonds_long"},
        actual_top5={"us_equities_value", "real_estate_reits", "us_bonds_long",
                     "us_equities_growth", "broad_commodities"},
        nber_recession=False,
        notes="Greenspan low rates + Bush tax cuts. Housing boom inizia.",
    ),
    HistoricalEpisode(
        name="2010 V-shape recovery post-GFC",
        start_year=2010, end_year=2010,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.7, "cpi_yoy": 1.6, "unrate": 9.8, "unrate_roc": -0.3,
            "vix": 23.0, "fed_funds": 0.25, "breakeven_10y": 2.2,
            "baa_10y_spread": 2.5, "pmi": 56.0, "yield_curve_spread": 2.8,
            "nfci": -0.2, "core_pce_yoy": 1.5, "consumer_sentiment": 72.0,
            "claims_roc": -3.5, "lei_roc": 1.5, "indpro_yoy": 5.0,
            "payrolls_yoy": 0.5, "housing_starts_yoy": 5.0,
            "acm_term_premium": 1.0,
        },
        actual_top3={"us_equities_growth", "em_equities", "broad_commodities"},
        actual_top5={"us_equities_growth", "em_equities", "broad_commodities",
                     "real_estate_reits", "gold"},
        nber_recession=False,
        notes="QE1 + fiscal stimulus, V-shape recovery. EM stelle.",
    ),
    HistoricalEpisode(
        name="2012 fiscal cliff scare",
        start_year=2012, end_year=2012,
        true_regime="deflation",
        indicators={
            "gdp_roc": 1.5, "cpi_yoy": 2.1, "unrate": 8.0, "unrate_roc": -0.2,
            "vix": 22.0, "fed_funds": 0.25, "breakeven_10y": 2.4,
            "baa_10y_spread": 2.8, "pmi": 49.0, "yield_curve_spread": 1.5,
            "nfci": 0.0, "core_pce_yoy": 2.0, "consumer_sentiment": 75.0,
            "claims_roc": -1.0, "lei_roc": 0.3, "indpro_yoy": 2.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 15.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_bonds_long", "gold", "real_estate_reits"},
        actual_top5={"us_bonds_long", "gold", "real_estate_reits",
                     "us_equities_growth", "tips_inflation_bonds"},
        nber_recession=False,
        notes="Eurozone scare + US debt ceiling. Mini-deflation.",
    ),
    HistoricalEpisode(
        name="2016 disinflation recovery mid",
        start_year=2016, end_year=2016,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 1.8, "cpi_yoy": 1.5, "unrate": 4.9, "unrate_roc": -0.2,
            "vix": 16.0, "fed_funds": 0.5, "breakeven_10y": 1.7,
            "baa_10y_spread": 2.2, "pmi": 52.0, "yield_curve_spread": 1.0,
            "nfci": -0.2, "core_pce_yoy": 1.7, "consumer_sentiment": 92.0,
            "claims_roc": -2.0, "lei_roc": 0.5, "indpro_yoy": -0.5,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 5.0,
            "acm_term_premium": 0.2,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "em_equities"},
        actual_top5={"us_equities_growth", "us_equities_value", "em_equities",
                     "real_estate_reits", "broad_commodities"},
        nber_recession=False,
        notes="Post-oil-crash recovery, low inflation. Trump election rally.",
    ),
    HistoricalEpisode(
        name="2017 tax cut acceleration",
        start_year=2017, end_year=2017,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.6, "cpi_yoy": 2.1, "unrate": 4.1, "unrate_roc": -0.4,
            "vix": 11.0, "fed_funds": 1.5, "breakeven_10y": 1.9,
            "baa_10y_spread": 1.7, "pmi": 58.0, "yield_curve_spread": 0.7,
            "nfci": -0.5, "core_pce_yoy": 1.7, "consumer_sentiment": 100.0,
            "claims_roc": -3.5, "lei_roc": 1.5, "indpro_yoy": 2.5,
            "payrolls_yoy": 1.6, "housing_starts_yoy": 4.0,
            "acm_term_premium": 0.0,
        },
        actual_top3={"us_equities_growth", "em_equities", "international_dm_equities"},
        actual_top5={"us_equities_growth", "em_equities", "international_dm_equities",
                     "us_equities_value", "real_estate_reits"},
        nber_recession=False,
        notes="VIX 11 (record low). TCJA tax cut. Stocks parabolic.",
    ),
    HistoricalEpisode(
        name="2019 mid-cycle Fed pivot",
        start_year=2019, end_year=2019,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 2.3, "cpi_yoy": 1.8, "unrate": 3.7, "unrate_roc": -0.1,
            "vix": 15.0, "fed_funds": 2.0, "breakeven_10y": 1.7,
            "baa_10y_spread": 1.9, "pmi": 50.0, "yield_curve_spread": 0.0,
            "nfci": -0.3, "core_pce_yoy": 1.7, "consumer_sentiment": 96.0,
            "claims_roc": -1.5, "lei_roc": 0.4, "indpro_yoy": -1.0,
            "payrolls_yoy": 1.5, "housing_starts_yoy": 2.0,
            "acm_term_premium": -0.2,
        },
        actual_top3={"us_equities_growth", "us_bonds_long", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_bonds_long", "real_estate_reits",
                     "us_equities_value", "gold"},
        nber_recession=False,
        notes="Fed cuts 75bps, soft landing. Stocks +30%, bonds rally.",
    ),
    HistoricalEpisode(
        name="2026 current sticky inflation late-cycle",
        start_year=2026, end_year=2026,
        true_regime="reflation",
        indicators={
            "gdp_roc": 0.5, "cpi_yoy": 3.95, "unrate": 4.3, "unrate_roc": 0.0,
            "vix": 17.3, "fed_funds": 4.5, "breakeven_10y": 2.5,
            "baa_10y_spread": 2.0, "pmi": 49.0, "yield_curve_spread": 0.5,
            "nfci": -0.5, "core_pce_yoy": 3.2, "consumer_sentiment": 53.0,
            "claims_roc": -12.0, "lei_roc": 0.0, "indpro_yoy": 1.0,
            "payrolls_yoy": 1.0, "housing_starts_yoy": 11.0,
            "acm_term_premium": 0.3,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "em_equities"},
        actual_top5={"us_equities_growth", "us_equities_value", "em_equities",
                     "real_estate_reits", "broad_commodities"},
        nber_recession=False,
        notes="Late-cycle reflation: CPI sticky 4%, GDP debole ma positivo, "
              "labor strong, NFCI loose. Pattern simile a tarda 2007 + 1980 inizio.",
    ),
    HistoricalEpisode(
        name="2013-14 post-taper-tantrum reflation",
        start_year=2013, end_year=2014,
        true_regime="reflation",
        indicators={
            "gdp_roc": 2.8, "cpi_yoy": 1.5, "unrate": 6.5, "unrate_roc": -0.5,
            "vix": 14.0, "fed_funds": 0.25, "breakeven_10y": 2.2,
            "baa_10y_spread": 1.8, "pmi": 56.0, "yield_curve_spread": 2.4,
            "nfci": -0.4, "core_pce_yoy": 1.5, "consumer_sentiment": 82.0,
            "claims_roc": -4.0, "lei_roc": 1.5, "indpro_yoy": 3.0,
            "payrolls_yoy": 1.8, "housing_starts_yoy": 15.0,
            "acm_term_premium": 0.5,
        },
        actual_top3={"us_equities_growth", "us_equities_value", "real_estate_reits"},
        actual_top5={"us_equities_growth", "us_equities_value", "real_estate_reits",
                     "international_dm_equities", "em_equities"},
        nber_recession=False,
        notes="Post-taper tantrum healing, S&P +32% 2013, +13% 2014. No gold.",
    ),
    HistoricalEpisode(
        name="1990 Japan asset bubble peak",
        start_year=1990, end_year=1990,
        true_regime="goldilocks",
        indicators={
            "gdp_roc": 4.8, "cpi_yoy": 3.0, "unrate": 2.1, "unrate_roc": 0.0,
            "vix": 17.0, "fed_funds": 8.0, "breakeven_10y": 2.7,
            "baa_10y_spread": 1.8, "pmi": 57.0, "yield_curve_spread": 0.3,
            "nfci": 0.1, "core_pce_yoy": 2.8, "consumer_sentiment": 100.0,
            "claims_roc": -1.0, "lei_roc": 0.8, "indpro_yoy": 4.5,
            "payrolls_yoy": 2.0, "housing_starts_yoy": 5.0,
            "acm_term_premium": 0.6,
        },
        actual_top3={"international_dm_equities", "us_equities_growth", "real_estate_reits"},
        actual_top5={"international_dm_equities", "us_equities_growth", "real_estate_reits", "us_equities_value", "gold"},
        nber_recession=False,
        notes="Japan Nikkei peak 38915, before 30y bear market. "
              "Bubble goldilocks signal — fragility latente.",
    ),
]


def get_episode_by_name(name: str) -> HistoricalEpisode | None:
    """Lookup episodio per nome (substring match case-insensitive)."""
    n = name.lower()
    for ep in HISTORICAL_EPISODES:
        if n in ep.name.lower():
            return ep
    return None


def episodes_by_regime(regime: str) -> list[HistoricalEpisode]:
    """Filtra episodi per true_regime."""
    return [ep for ep in HISTORICAL_EPISODES if ep.true_regime == regime]


def regime_distribution() -> dict[str, int]:
    """Counts per regime nel dataset labeled."""
    out: dict[str, int] = {}
    for ep in HISTORICAL_EPISODES:
        out[ep.true_regime] = out.get(ep.true_regime, 0) + 1
    return out
